#!/bin/bash

data=$(ls -lt ../pngimage-Techniques.AFL_CMIN*.data | rev | cut -f1 -d" " | rev)
cat ${data} | grep -v "#" | awk '{print $1 $7}' | sed  's/\,$/ /g' | sed  's/\%//g' > file1.data

data=$(ls -lt ../pngimage-Techniques.AFL_MO_*.data | rev | cut -f1 -d" " | rev)
cat ${data} | grep -v "#" | awk '{print $1 $7}' | sed  's/\,$/ /g' | sed  's/\%//g' > file2.data

Rscript sample2.r
