#!/bin/bash

cat ../pngimage-Techniques.AFL_CMIN-2019.04.14-20:28:08.data | grep -v "#" | awk '{print $1 $7}' | sed  's/\,$/ /g' | sed  's/\%//g' > file1.data
cat ../pngimage-Techniques.AFL_MO_SELECTION-2019.04.14-19:43:06.data | grep -v "#" | awk '{print $1 $7}' | sed  's/\,$/ /g' | sed  's/\%//g' > file2.data

Rscript sample2.r